name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
env:
  RUNS_ON: ubuntu-latest
  ARTIFACT_NAME: GithubActionDemo.${{ github.head_ref }}.${{ github.sha }}.zip

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  initialization:
    runs-on: ubuntu-latest
    name: Initialization
    steps:
      - run: echo "Installing dependencies."
      - run: sudo apt-get install zip gzip tar
      - run: echo "Configure AWS credentials."
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GithubActionDemo
          aws-region: us-east-1  
    
  build-stage:
    runs-on: ubuntu-latest
    name: Build Stage
    needs: initialization
    steps:
      - run: echo "Nothing to build in a python package. Succeeding directly."

  test-stage:
    runs-on: ubuntu-latest
    name: Test Stage
    needs: build-stage
    steps:
      - run: echo "Checking out the repository."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "Running unittest in the repository."
      - run: python3 -m unittest

  packaging-stage:
    runs-on: $RUNS_ON
    name: Packaging Stage
    needs: test-stage
    steps:
      - run: echo "Creating an artifact."
      - run: echo "Checking out the repository."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: zip -r ${{ env.ARTIFACT_NAME }} GithubActionDemo
      - run: echo "Uploading the artifact to S3."
      - run: aws s3 ${{ env.ARTIFACT_NAME }} s3://ryansblog-lab/
